site_name: 线性代数
site_url: https://fleetinglore.github.io/xxds

nav:
  - 第一章  行列式:
      - 1. 二阶与三阶行列式: 1/1.md
      - 2. 全排列与对换: 1/2.md
      - 3. n 阶行列式的定义: 1/3.md
      - 4. 行列式的性质: 1/4.md
      - 5. 行列式的按行(列)展开: 1/5.md

  - 第二章  矩阵及其运算:
      - 1. 线性方程组和矩阵: 2/1.md
      - 2. 矩阵的运算: 2/2.md
      - 3. 逆矩阵: 2/3.md
      - 4. 克拉默法则: 2/4.md
      - 5. 矩阵分块法: 2/5.md

  - 第三章  矩阵的初等变换与线性方程组:
      - 1. 矩阵的初等变换: 3/1.md
      - 2. 矩阵的秩: 3/2.md
      - 3. 线性方程组的解: 3/3.md

  - 第四章  向量组的线性相关性:
      - 1. 向量组及其线性组合: 4/1.md
      - 2. 向量组的线性相关性: 4/2.md
      - 3. 向量组的秩: 4/3.md
      - 4. 线性方程组解的结构: 4/4.md
      - 5. 向量空间: 4/5.md

  - 第五章  相似矩阵及二次型:
      - 1. 向量的内积、长度及正交性: 5/1.md
      - 2. 方阵的特征值与特征向量: 5/2.md
      - 3. 相似矩阵: 5/3.md
      - 4. 对称矩阵的对角化: 5/4.md
      - 5. 二次型及其标准形: 5/5.md
      - 6. 用配方法化二次型成标准形: 5/6.md
      - 7. 正定二次型: 5/7.md

  - 第六章  线性空间与线性变换:
      - 1. 线性空间的定义和性质: 6/1.md
      - 2. 维数、基与坐标: 6/2.md
      - 3. 基变换与坐标变换: 6/3.md
      - 4. 线性变换: 6/4.md
      - 5. 线性变换的矩阵表示式: 6/5.md

theme:
  name: material
  palette:
    # 亮色模式
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # 深色模式
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji # 可选：支持表情符号
  - footnotes # 可选：支持脚注

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
